name: Laravel CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root # Senha do root aqui
          MYSQL_DATABASE: clinida_estetica_testing # Nome do banco de dados
        ports:
          - 3306:3306 # Expõe a porta 3306 do container
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -uroot -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Validate syntax
        run: find . -name "*.php" -not -path "./vendor/*" -exec php -l {} \;

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3.4"
          extensions: mbstring, pdo, pdo_mysql
          coverage: none

      - name: Install Composer dependencies
        run: |
          composer install --prefer-dist --no-progress --no-suggest
          composer dump-autoload

      - name: Copy environment file
        run: cp .env.testing .env

      - name: Copy environment file to test
        run: cp .env.testing.pipeline .env.testing

      - name: Generate application key
        run: php artisan key:generate --env=testing

      - name: Wait for MySQL
        run: |
          for i in {1..30}; do
            if mysqladmin ping -h 127.0.0.1 -P 3306 --silent; then
              echo "MySQL is ready!"
              break
            else
              echo "Waiting for MySQL... Attempt $i"
              sleep 5
            fi
          done

      - name: Run migrations
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1 # Aqui, usa localhost ou IP do container do serviço MySQL
          DB_PORT: 3306
          DB_DATABASE: clinida_estetica_testing
          DB_USERNAME: root
          DB_PASSWORD: root
        run: php artisan migrate --env=testing --force

      - name: Run tests
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1 # Aqui também
          DB_PORT: 3306
          DB_DATABASE: clinida_estetica_testing
          DB_USERNAME: root
          DB_PASSWORD: root
        run: php artisan test
